### PR TITLE
Bump MockServer to 5.13.2

### PR DESCRIPTION
**Pull request by gwenneg**
Our build is unstable on GitHub when the `mockserver-client-java` version is higher than `5.5.4`.

This branch will be used to try and stabilize the build with the latest mockserver version.

### CODE REVIEW

**Comment by bennetelli** [comment]
haha! We are doing the same with different PRs :-D https://github.com/RedHatInsights/notifications-backend/pull/1137

**Comment by bennetelli** [comment]
also posting it here. There is also a "real" mockserver docker image: https://hub.docker.com/r/mockserver/mockserver 
where the jamesdbloom user is contributing to as well. Will give that one a try. It probably doesnt change something, but we will see.

**Comment by gwenneg** [comment]
15 consecutive runs without a single failure... I think this is stable now 😃

This PR now replaces our old MockServer Docker image usage with the MockServer Java API which offers exactly the same features. See the [MockServer doc](https://www.mock-server.com/mock_server/running_mock_server.html#client_api) for more details about it. I think it's even better than before because we can have the MockServer log entries at the same place than our log entries, which will make debugging easier in some cases.

I disabled the MockServer log by default to reduce the noise during a build. It can be enabled using the following build argument:
```
-Dmockserver.logLevel=WARN|INFO|DEBUG|TRACE
```
Details about each logging level are available in the [doc](https://www.mock-server.com/mock_server/debugging_issues.html).

**Comment by bennetelli** [comment]
> 15 consecutive runs without a single failure... I think this is stable now smiley
> 
> This PR now replaces our old MockServer Docker image usage with the MockServer Java API which offers exactly the same features. See the [MockServer doc](https://www.mock-server.com/mock_server/running_mock_server.html#client_api) for more details about it. I think it's even better than before because we can have the MockServer log entries at the same place than our log entries, which will make debugging easier in some cases.
> 
> I disabled the MockServer log by default to reduce the noise during a build. It can be enabled using the following build argument:
> 
> ```
> -Dmockserver.logLevel=WARN|INFO|DEBUG|TRACE
> ```
> 
> Details about each logging level are available in the [doc](https://www.mock-server.com/mock_server/debugging_issues.html).

we could add this hint to the README so everyone knows about it.

**Review by bennetelli — APPROVED** [review]
Good job! LGTM

**Comment by bennetelli** [comment]
@gwenneg woah! This PR fixes my local build issues I have with testcontainers/java/running tests/... <3

**Comment by gwenneg** [comment]
> we could add this hint to the README so everyone knows about it.

Good idea, thanks! I updated the readme 😃

**Comment by gwenneg** [comment]
I will run the tests an another 10 times before merging to reaaaaally confirm the stability.

**Comment by bennetelli** [comment]
> I will run the tests an another 10 times before merging to reaaaaally confirm the stability.

Okay :-D I would say it's safe, but do it if you want :-D

**Comment by gwenneg** [comment]
10 more successful test runs done, I'm merging 🎉

**Pull request merged**
