### PR TITLE
NOTIF-150 Fix behavior group actions

### PR DESCRIPTION
**Pull request by josejulio**
With NOTIF-193, we now have to load manually the endpoints properties

This fixes an issue seen in ci/qa

### CODE REVIEW

**Comment by josejulio** [comment]
//cc @gwenneg

**Comment by pilhuhn** [comment]
Tests fail to create the default-BG now. This does not seem related to the code change though.

**Comment by josejulio** [comment]
> Tests fail to create the default-BG now. This does not seem related to the code change though.

It's actually failing on the endpoint modified. I'll take a look

**Review by pilhuhn — APPROVED** [review]

**Comment by josejulio** [comment]
Thanks!

**Pull request merged**
