### PR TITLE
Pushes coverage to codecov.io

### PR DESCRIPTION
**Pull request by josejulio**
Do we have coverage already somewhere else?
This seems to be working.

https://app.codecov.io/gh/RedHatInsights/notifications-backend/branch/coverage-test

### CODE REVIEW

**Comment by josejulio** [comment]
@pilhuhn I recall you did some thing with jacoco before. It didn't work? or maybe we have the coverage somewhere?

**Comment by gwenneg** [comment]
Did you look for coverage in our internal tool?

**Comment by josejulio** [comment]
Didn't found any reported coverage else where. Maybe this is something we can start using.

**Review by gwenneg — COMMENTED** [review]
https://quarkus.io/guides/tests-with-coverage may contain useful information about this.

**Review by bennetelli — APPROVED** [review]
in comparison to this: https://github.com/codecov/example-java it looks good :)

let's give it a try :)

**Comment by josejulio** [comment]
I think it's finally working - had issues with the dependency en `dependencyManagement` instead of `dependencies`

**Pull request merged**
