### PR TITLE
NOTIF-603 Add org_id indexes for the Event Log

### PR DESCRIPTION
**Pull request by gwenneg**
Current `event` indexes retrieved on prod with gabi:
```
CREATE UNIQUE INDEX pk_event ON public.event USING btree (id)
CREATE INDEX ix_event_index_only_scan ON public.event USING btree (account_id, bundle_id, application_id, event_type_display_name, created DESC, id)
CREATE INDEX ix_event_account_id ON public.event USING btree (account_id, created DESC, id)
CREATE INDEX ix_event_account_id_application_id ON public.event USING btree (account_id, application_id, created DESC, id)
CREATE INDEX ix_event_org_id ON public.event USING btree (org_id)
```

### CODE REVIEW

**Review by josejulio — APPROVED** [review]
lgtm

**Comment by gwenneg** [comment]
⚠️ **DO NOT MERGE** ⚠️

While the script would work as intended, we will probably not migrate the data that way.

**Comment by gwenneg** [comment]
:information_source: The `event` table data has been migrated on prod. We're ready to create the new indexes now.

:warning: The indexes creation will require a lot of times, probably something between 5 and 10 minutes. The health checks from the ClowdApp templates will need to be temporarily adjusted when this PR is deployed.

**Comment by gwenneg** [comment]
I increased the version of the migration script because of a conflict with another merged script.

This PR will be merged right before the prod deployment, next week.

**Review by josejulio — APPROVED** [review]

**Comment by gwenneg** [comment]
I changed the probes configuration to allow a 20 minutes startup time:
initialDelaySeconds (40) + periodSeconds (10) * failureThreshold (116) = 1200 seconds / 20 minutes

**Pull request merged**
