### PR TITLE
[RHCLOUD-30599] Design Tasks email templates

### PR DESCRIPTION
**Pull request by g-duval**

### CODE REVIEW

**Review by MikelAlejoBR — APPROVED** [review]
LGTM!

**Comment by gwenneg** [comment]
Don't we need more templates for `executed-task-started` and `executed-task-cancelled`?

**Comment by g-duval** [comment]
> Don't we need more templates for `executed-task-started` and `executed-task-cancelled`?

According https://issues.redhat.com/browse/RHCLOUD-26145, we don't.

**Review by gwenneg — APPROVED** [review]
LGTM

**Pull request merged**
