### PR TITLE
NOTIF-177 Add SQL relationship to endpoint_email_subscriptions

### PR DESCRIPTION
**Pull request by gwenneg**
yuml diagram

### CODE REVIEW

**Comment by gwenneg** [comment]
Before SQL migration:

```
notifications=# \d endpoint_email_subscriptions
                              Table ½ public.endpoint_email_subscriptions ╗
      Colonne      |          Type          | Collationnement | NULL-able |          Par dÚfaut
-------------------+------------------------+-----------------+-----------+-------------------------------
 account_id        | character varying(50)  |                 | not null  |
 user_id           | character varying(50)  |                 | not null  |
 subscription_type | character varying(50)  |                 | not null  |
 application       | character varying(255) |                 | not null  | 'policies'::character varying
 bundle            | character varying(255) |                 | not null  | 'insights'::character varying
Index :
    "endpoint_email_subscriptions_pkey" PRIMARY KEY, btree (account_id, user_id, subscription_type, application, bundle)

notifications=# select * from bundles;
                  id                  | name |       display_name       |          created           | updated
--------------------------------------+------+--------------------------+----------------------------+---------
 393eec9a-b9aa-4797-b207-687886d1e11d | rhel | Red Hat Enterprise Linux | 2021-04-22 14:23:12.645647 |
(1 ligne)

notifications=# select * from applications;
                  id                  |   name   | display_name |          created           | updated |              bundle_id
--------------------------------------+----------+--------------+----------------------------+---------+--------------------------------------
 e9872790-af1d-4b58-a354-9e26849ec7fa | policies | Policies     | 2021-04-22 14:23:12.557356 |         | 393eec9a-b9aa-4797-b207-687886d1e11d
(1 ligne)

notifications=# select * from endpoint_email_subscriptions;
 account_id | user_id | subscription_type | application | bundle
------------+---------+-------------------+-------------+---------
 12345      | 54321   | DAILY             | policies    | rhel
 12345      | 54321   | DAILY             | unknown     | rhel
 12345      | 54321   | DAILY             | policies    | unknown
(3 lignes)
```

After SQL migration:

```
notifications=# \d endpoint_email_subscriptions
                    Table ½ public.endpoint_email_subscriptions ╗
      Colonne      |         Type          | Collationnement | NULL-able | Par dÚfaut
-------------------+-----------------------+-----------------+-----------+------------
 account_id        | character varying(50) |                 | not null  |
 user_id           | character varying(50) |                 | not null  |
 subscription_type | character varying(50) |                 | not null  |
 application_id    | uuid                  |                 | not null  |
Index :
    "pk_endpoint_email_subscriptions" PRIMARY KEY, btree (account_id, user_id, subscription_type, application_id)
Contraintes de clÚs ÚtrangÞres :
    "fk_endpoint_email_subscriptions_application_id" FOREIGN KEY (application_id) REFERENCES applications(id)

notifications=# select * from endpoint_email_subscriptions;
 account_id | user_id | subscription_type |            application_id
------------+---------+-------------------+--------------------------------------
 12345      | 54321   | DAILY             | e9872790-af1d-4b58-a354-9e26849ec7fa
(1 ligne)
```

**Comment by gwenneg** [comment]
@theute I'll need your approval on the data migration: is that OK to delete from `endpoint_email_subscriptions` all records that would not contain a valid `bundle`/`application` couple? We may want to check if such records exist first on stage/prod. A temporary API can be added to do that if necessary.

@josejulio It would be great if you could confirm that everything's still running fine in the UI with this PR.

**Comment by theute** [comment]
> @theute I'll need your approval on the data migration: is that OK to delete from endpoint_email_subscriptions all records that would not contain a valid bundle/application couple? We may want to check if such records exist first on stage/prod. A temporary API can be added to do that if necessary.

Yes, I see no reason why we would have records with invalid bundle/application that we would want to keep.

**Comment by josejulio** [comment]
> @josejulio It would be great if you could confirm that everything's still running fine in the UI with this PR.

Code looks fine, I'll do some tests with ci

**Comment by gwenneg** [comment]
@theute Can we merge this today or is it better to wait for next week because of the data migration?

**Pull request merged**
