### PR TITLE
feat: add instance created / deleted for RHOSAK application

### PR DESCRIPTION
**Pull request by machi1990**
Closes https://issues.redhat.com/browse/MGDSTRM-5528 and https://issues.redhat.com/browse/MGDSTRM-5529

/cc @akoserwal @davidffrench @josejulio @gwenneg

### CODE REVIEW

**Review by gwenneg — APPROVED** [review]
LGTM

**Comment by gwenneg** [comment]
Should I wait for a review from @akoserwal or @davidffrench before the merge?

**Review by davidffrench — COMMENTED** [review]
Abhishek is out today. This looks good to me and if there is feedback from content services or UX, this can be updated.

**Comment by machi1990** [comment]
@gwenneg thanks for the approval. Let's get this in, as David said we'll update it based on our tests in CI/stage env and feedback from UX.

**Pull request merged**
