### PR TITLE
NOTIF-336 Clowderize pr_check.sh

### PR DESCRIPTION
**Pull request by gwenneg**

### CODE REVIEW

**Comment by theute** [comment]
https://www.youtube.com/watch?v=A2VpR8HahKc

**Comment by gwenneg** [comment]
IQE tests are disabled because of the following error:
```
15:01:30 ./mc mirror --overwrite minio/$pod-artifacts artifacts/
15:01:30 mc: <ERROR> Unable to stat source `minio/notifications-backend-smoke-tests-iqe-qryw08y--1-h5947-artifacts`. Bucket name cannot be longer than 63 characters.
```

**Comment by gwenneg** [comment]
This is ready for a review/merge.

Backend is almost working (see my previous comment about IQE tests).
I will work on aggregator later, for now I want to focus on `-gw`.

**Comment by gwenneg** [comment]
Testing an IQE tests fix from the bonfire team.

**Comment by gwenneg** [comment]
Test complete. We now have a successful IQE tests run included in the PR check script.

**Pull request merged**
