### PR TITLE
Pom updates for a more reproducible build

### PR DESCRIPTION
**Pull request by pilhuhn**
Basically Level 1 of https://github.com/rfichtner/maven-survival-guide

We (only) require Maven 3.8.1 as Quarkus uses that version. Locally it works well with 3.8.6

### CODE REVIEW

**Review by bennetelli — APPROVED** [review]
lgtm

**Comment by bennetelli** [comment]
it's your decision. Do whatever you think you need to do.

**Review by gwenneg — APPROVED** [review]
LGTM

**Comment by gwenneg** [comment]
Rebased onto `master`.

**Pull request merged**
