### PR TITLE
Openshift

### PR DESCRIPTION
**Pull request by adamruzicka**
Adds support for connecting to password protected redis.

Images used in openshift should be based on RHEL, changed Redis and Postgres services to use RHEL based images to make the deployment closer to the openshift one.

### CODE REVIEW

**Comment by adamruzicka** [comment]
More changes incoming

**Comment by ShimShtein** [comment]
@adamruzicka Travis is not happy for ruby 2.6. Is it related?

**Comment by adamruzicka** [comment]
I don't think so, all the PRs started failing on ruby 2.6

**Comment by bastilian** [comment]
The postresql image won't come up with this image, it looks like it is missing environment variables.

**Comment by bastilian** [comment]
👍 now everything works as expected again. :)

**Comment by bastilian** [comment]
Merged! Thank you @adamruzicka!

**Pull request merged**
