### PR TITLE
NOTIF-444 Change the way of creating dynamic counters

### PR DESCRIPTION
**Pull request by bennetelli**

### CODE REVIEW

**Comment by bennetelli** [comment]
as written to you in Slack. I just want to test it on stage quickly. If it's working then it's fine. If not, I will revert it so others are not affected by it.

**Review by josejulio — APPROVED** [review]
OK, lets try.

**Comment by gwenneg** [comment]
What was the conclusion of the tests on stage? Is it safe to be deployed on prod?

**Comment by bennetelli** [comment]
> What was the conclusion of the tests on stage? Is it safe to be deployed on prod?

It's "safe" in that way that the tags for the processor_email_processed metrics are still not present on stage and prod.
So it's safe to be deployed on prod. We didn't have these tags before this PR and with this one we will also not have it on prod. So it doesn't add something useful for customers, but at least it doesn't destroy something.

**Comment by gwenneg** [comment]
Sounds safe to me, thanks!

**Pull request merged**
