### PR TITLE
[RHCLOUD-35969] drop orphans system endpoints

### PR DESCRIPTION
**Pull request by g-duval**

### CODE REVIEW

**Review by MikelAlejoBR — APPROVED** [review]
LGTM! One question: we don't need to check the `endpoint_event_type` table, right?

**Review by gwenneg — APPROVED** [review]
LGTM

**Review by gwenneg — CHANGES_REQUESTED** [review]
The SQL file needs to be renamed to `V1.106`.

**Review by gwenneg — APPROVED** [review]

**Comment by g-duval** [comment]
> LGTM! One question: we don't need to check the `endpoint_event_type` table, right?

No we don't have to @MikelAlejoBR, because those endpoints were generated automatically by aggregation process which skips event_type associations.

**Pull request merged**
