### PR TITLE
Add HTML templates for Advisor daily email

### PR DESCRIPTION
**Pull request by mhuth**
This depends on the Java stuff Paul Wayper is working on

For https://issues.redhat.com/browse/ADVISOR-2876 as part of https://issues.redhat.com/browse/ADVISOR-2022

### CODE REVIEW

**Comment by mhuth** [comment]
What the marked up email looks like ... 
Screenshot from 2022-12-12 16-43-36

This is the mock for comparison: https://www.sketch.com/s/dbb63fd6-4259-400c-853f-3dcd66ac8d04/a/eKvgvya

**Comment by mhuth** [comment]
Thanks for the review @josejulio.  Any chance you can merge it?  I don't have permissions to do that.  If there are any changes that need to be made I'll push them up in a separate PR.

**Comment by mhuth** [comment]
> lgtm - i didn't cross check the data, but the template looks good. Thanks for using the template renderer!

Where is the code for the template render BTW?  I have some changes I'd like to try/suggest making to it.

**Comment by josejulio** [comment]
> Where is the code for the template render BTW? I have some changes I'd like to try/suggest making to it.

This is an internal page where you can try the template. Note that it does not support multiple files, so you have to copy all into a single file.

https://internal.console.stage.redhat.com/api/notifications/internal/#/email

**Pull request merged**
