### PR TITLE
Limit what we show in logs

### PR DESCRIPTION
**Pull request by theute**
This is a proposal to not log potentially private info but the info that would be useful to us.
A log line would look like:
`Processing received payload: (123456) rhel/policies/triggered-policy`

Additional I changed from DEBUG to INFO

### CODE REVIEW

**Comment by gwenneg** [comment]
The new message LGTM but I wonder if we should keep logging the full payload at `fine` level in case of failure (`Could not process the payload`). When an `AvroTypeException` is thrown, the failure cause is clear, but it might now be the case if another kind of exception is thrown.

**Comment by gwenneg** [comment]
If we keep logging the payload in case of failure, we should probably do that at the `onItemOrFailure()` step.

**Comment by gwenneg** [comment]
Can a payload contain info that should never be logged?

**Comment by josejulio** [comment]
> Can a payload contain info that should never be logged?

I guess it could, up to the application, the payloads contain free-form data on `payload` and `context`

**Comment by theute** [comment]
In case of failure we should still know why it failed though (maybe strip the data and context sections)

**Comment by josejulio** [comment]
> In case of failure we should still know why it failed though (maybe strip the data and context sections)

What about (in the future) if we store last X failing payloads to be able to show them in the internal frontend to follow up?

**Comment by theute** [comment]
Once we have the admin UI we should keep some in memory yes.
In the meantime, the log here is what help us help them

Let's improve on the existing, if we are ok with the positive case. We can move where we log for failures but I'm not sure I understand how to do it (this mutiny thing is new to me)

**Comment by josejulio** [comment]
You can change https://github.com/RedHatInsights/notifications-backend/pull/215/files#diff-0e31a1d690e7134bc5653f78759c63ef9bf30220941dc854fdf5296cad9db840R68 to something like:
```
log.log(Level.INFO, "Could not process the payload: " + input.getPayload(), t);
```
That will log if there is any error in the whole process (is that correct @gwenneg ?)

**Comment by gwenneg** [comment]
That's exactly what I had in mind.

**Comment by theute** [comment]
Sorry, I'm still unclear where exactly or just change line 68 ?

**Comment by gwenneg** [comment]
You need to replace line 68 from:
`log.log(Level.INFO, "Could not process the payload", t);`
to:
`log.log(Level.INFO, "Could not process the payload: " + input.getPayload(), t);`

Now, do we want to log that at `INFO` or `FINE` level? I'd say `FINE` but I'm not sure.

**Comment by theute** [comment]
Ok I get why I was confused at first, the log line already shows the payload in the error message (you couldn't know), so I don't think it adds anything here.

**Comment by theute** [comment]
Scratch that, I'm stupid / need sleep...

**Review by pilhuhn — APPROVED** [review]

**Pull request merged**
