### PR TITLE
Clowdapp files for OpenBridge use

### PR DESCRIPTION
**Pull request by pilhuhn**
Those externalise the entries from application.properties for Clowder usage.

### CODE REVIEW

**Review by gwenneg — COMMENTED** [review]
Shouldn't some of them (passwords in particular) come from the vault?

**Comment by pilhuhn** [comment]
In the long(er) run yes. For stage and their 'stable' env it is less of a deal (IMO)

**Review by gwenneg — APPROVED** [review]
This PR doesn't leak anything so LGTM I guess.

We need to be careful with the params that will be put in app-interface though.

**Comment by pilhuhn** [comment]
Test failure is an issue in the test itself.

**Comment by pilhuhn** [comment]
Changing to a draft. I will change the way to 'find' a bridge to using its uuid instead of the name.

**Comment by pilhuhn** [comment]
Follow up to #1060

**Pull request merged**
