### PR TITLE
NOTIF-190 Add aggregator

### PR DESCRIPTION
**Pull request by bennetelli**

### CODE REVIEW

**Comment by theute** [comment]
See comment about branches here: https://github.com/RedHatInsights/notifications-backend/pull/328#issuecomment-870557376 ;-)
Also I though we were *not* adding submodules ?

**Comment by bennetelli** [comment]
"Note: In the future please don't push to this repo directly (even with a new branch like here) but always push to your own clone/branch before you create a PR."

Does it mean I should fork the repository before?

**Comment by bennetelli** [comment]
Locally there was no difference. I didn't add the submodule explicitly. This seems to be the default.

**Comment by theute** [comment]
Yes :
1) otherwise you leave branches behind you: https://github.com/RedHatInsights/notifications-backend/branches https://github.com/RedHatInsights/policies-engine/branches
2) as a rule of thumb you should never push to this repo directly

**Comment by theute** [comment]
Did you delete the .git in the aggregator directory before you pushed ?

**Comment by theute** [comment]
It's definitely wrong, the icon also shows a submodule:
image
And then it can't be browsed:
https://github.com/RedHatInsights/notifications-backend/tree/add_aggregator

**Comment by bennetelli** [comment]
> Did you delete the .git in the aggregator directory before you pushed ?

I would say yes.

**Pull request closed without merging**
