### PR TITLE
RHCLOUD-29294 Setup emails for RBAC request-access event type

### PR DESCRIPTION
**Pull request by josejulio**

### CODE REVIEW

**Comment by josejulio** [comment]
@g-duval Do i need to manually setup these templates on the admin-ui?

**Comment by g-duval** [comment]
Nop you don't need to setup manually the template from admin UI.
Because template migration step runs at every startup, it will ba added automaticaly on next deployment.
Ths template looks fine good to me, could you please consider to add a minimal test case for this new one on [TestRbacTemplate](https://github.com/RedHatInsights/notifications-backend/blob/master/engine/src/test/java/com/redhat/cloud/notifications/templates/TestRbacTemplate.java|TestRbacTemplate) ?
The purpose of this test is just to guarantee template rendering ;)

**Comment by josejulio** [comment]
@g-duval Updated the tests. Moved a bit the setup to prevent repeating the event types multiple times

**Review by g-duval — APPROVED** [review]
LGTM

**Pull request merged**
