### PR TITLE
NOTIF-267 Retry on RBAC call failure

### PR DESCRIPTION
**Pull request by gwenneg**
This is based on Mutiny's [retry capabilities](https://smallrye.io/smallrye-mutiny/getting-started/retry).

### CODE REVIEW

**Comment by bennetelli** [comment]
I need to merge this PR first: https://github.com/RedHatInsights/notifications-backend/pull/398

**Comment by bennetelli** [comment]
The ci.ext.devshift.net PR build takes very long unfortunately.. it spends much time waiting for the yarn stuff.

**Comment by gwenneg** [comment]
Yes but that's worth the wait, I really like having the Jenkins build status in the GH PRs 😃

**Comment by bennetelli** [comment]
> Yes but that's worth the wait, I really like having the Jenkins build status in the GH PRs smiley

Yes, indeed. It's better than having green GitHub builds and red jenkins ones for days. But there's still room for improvement :)

**Comment by theute** [comment]
All green now, but indeed, the new check took 22min :-/ (and those are done in series (not parallel))

**Comment by gwenneg** [comment]
It was taking 22 minutes (more or less) before as well, we just didn't pay attention to one of the checks. We can always merge a PR without waiting for the Jenkins build in case of emergency.

**Comment by gwenneg** [comment]
> We can always merge a PR without waiting for the Jenkins build in case of emergency.

Considering most emergencies imply redeploying which itself requires the Jenkins build to be done, that doesn't actually make sense 😄

**Comment by theute** [comment]
AFAICT it used to take 7 - 8 min.

**Review by josejulio — APPROVED** [review]
lgtm

**Pull request merged**
