### PR TITLE
Application targets

### PR DESCRIPTION
**Pull request by burmanm**

### CODE REVIEW

**Comment by burmanm** [comment]
@josejulio Could you test your UI requirements against this and let me know what you need?

**Comment by josejulio** [comment]
> @josejulio Could you test your UI requirements against this and let me know what you need?

Yes, checking...

**Comment by josejulio** [comment]
After some initial look with the API and the design:

- I would need an `/eventTypes` endpoint to be the backbone of the "Notification List" UI
 - It needs filtering by `event.name`, `application` (could be the id I think), `action` (`send to notification drawer` `send email`, `integration webhook ABC`) and the `recipient` (currently for "notifications" to who the email is being sent or the notification drawer)
 - Sorting by event_type
 - An additional sorting by `application` to be able to build the grouped list.
 - Provide paging options (with total count :D)
 - Preferably, each eventType should have the application (name and id); to save a request for every eventType, else a "get application id" for `eventType.id` would help.

The reason I ask for a `/eventTypes` and not using `/application` is because the paging and the sorting by eventType would be harder that way.

**Comment by burmanm** [comment]
Action? You mean endpoints linked to the application+tenant+eventType ?

**Comment by josejulio** [comment]
> Action? You mean endpoints linked to the application+tenant+eventType ?

Yes, and not sure if `Send email` or `Send to notification drawer`  are  `endpoints` too.

Screenshot_2020-10-05_13-08-15

**Comment by burmanm** [comment]
I thought we always send to notification drawer, but yes it would be an endpoint also. Emails are endpoints (although there's no support for emails in this app) like previously.

**Comment by burmanm** [comment]
``Preferably, each eventType should have the application (name and id); to save a request for every eventType, else a "get application id" for eventType.id would help.``

I don't get this. The eventTypes and applications are not user maintained. Each event type is unique (even with same name), so the endpoints are linked to it by the eventTypeId, no need to know the application name/id for it.

**Comment by josejulio** [comment]
> I thought we always send to notification drawer

From the mocks, it looks like its opt-in

Also forgot to mention that we have `default behavior` for each tentant, it has a sets of `endpoints` also, much like an `eventType`

> I don't get this. The eventTypes and applications are not user maintained. Each event type is unique (even with same name), so the endpoints are linked to it by the eventTypeId, no need to know the application name/id for it.

I would need the application name for showing it on the UI. I don't really need the application id.

**Comment by burmanm** [comment]
From the ApplicationService, the user will be able to see only: 

```java
    @GET
    @Path("/{id}/eventTypes")
    public Multi<EventType> getEventTypes(@PathParam("id") UUID applicationId);

    @GET
    @Path("/{id}")
    public Uni<Application> getApplication(@PathParam("id") UUID id);
```

I originally thought you might want to get the list of applications and inside each application there's the even types available (Set<EventType>). The API doesn't allow you to request them filled yet. How would it work the other way?

**Comment by burmanm** [comment]
What I mean is, which way do you prefer:

a) (Current structure)

```json
{
    "policies": [
        {
            "id": 1,
            "name": "All"
        }
    ],
    "advisor": [
        {
            "id": 2,
            "name": "Dummy event"
        },
        {
            "id": 3,
            "name": "Security issue"
        },
        {
            "id": 4,
            "name": "All"
        }
    ]
}
```

b) This is how I understood your leveling?

```json
[
    {
        "id": 1,
        "name": "All",
        "application": "Policies"
    },
    {
        "id": 4,
        "name": "All",
        "application": "Advisor"
    },
    {
        "id": 2,
        "name": "Dummy event",
        "application": "Advisor"
    },
    {
        "id": 3,
        "name": "Security issue",
        "application": "Advisor"
    }
]
```

**Comment by josejulio** [comment]
> b) This is how I understood your leveling?

This would work better for the list, see: https://ci.cloud.redhat.com/beta/settings/notifications and https://github.com/RedHatInsights/notifications-frontend/blob/master/src/pages/Notifications/List/Page.tsx#L73-L160

**Comment by josejulio** [comment]
The reason is that the UI shows eventTypes, grouped by none / application. `a)` is already grouped and could work, but we need to be able to group by: None and sort by the event name (and pagination of x eventType per page)

**Comment by burmanm** [comment]
Just remember that event name is not unique.

**Pull request merged**
