### PR TITLE
NOTIF-291 Finish the event log schema migration and clean code

### PR DESCRIPTION
**Pull request by gwenneg**
This PR will be a draft until I've verified the data migration won't cause any issue with the current production data (I'll write app-interface queries tomorrow) but you can already review it.

### CODE REVIEW

**Review by josejulio — APPROVED** [review]

**Comment by gwenneg** [comment]
```
  # Check that the notification_history.event_id field is never null before adding a not null constraint.
  - "select count(id) from notification_history where event_id is null;"
  # Check that the event.event_type_id field is never null before adding a not null constraint.
  - "select count(id) from event where event_type_id is null;"
```

**Comment by gwenneg** [comment]
The queries result is actually normal. We didn't wait for the 31 days retention delay so the `event` table contains records resulting from the `V.1.27.0` data migration. These records don't have a link between `event` and `event_type`. They will be purged soon by `EventLogCleaner`.

Let's put this PR on hold for now. I'll check the prod database again in 7 days.

**Comment by gwenneg** [comment]
```
  # Check that the notification_history.event_id field is never null before adding a not null constraint.
  - "select count(id) from notification_history where event_id is null;"
  # Check that the event.event_type_id field is never null before adding a not null constraint.
  - "select count(id) from event where event_type_id is null;"
```
```
 count
-------
     0
(1 row)

 count
-------
     0
(1 row)
```

**Comment by gwenneg** [comment]
Rebased to fix conflicts.

**Pull request merged**
