### PR TITLE
[RHCLOUD-23853] Update default email template

### PR DESCRIPTION
**Pull request by g-duval**
image

### CODE REVIEW

**Review by josejulio — APPROVED** [review]
lgtm

**Comment by gwenneg** [comment]
No feature flag for that one?

**Comment by g-duval** [comment]
> 

No because as I undersood, this default template usage is already behind a feature flag enabled on stage only.
It should never be sent as it is to a real enduser.

**Comment by gwenneg** [comment]
Makes sense 👍

**Pull request merged**
