### PR TITLE
First check if the Endpoint is really a camel one before proceeding.

### PR DESCRIPTION
**Pull request by pilhuhn**

### CODE REVIEW

**Comment by gwenneg** [comment]
`EndpointService` has been [renamed](https://github.com/RedHatInsights/notifications-backend/pull/1077) to `EndpointResource`.

**Review by gwenneg — APPROVED** [review]
LGTM

**Comment by pilhuhn** [comment]
Le sigh.. after GH build was happy after 3 runs, the other one has issues

**Comment by gwenneg** [comment]
Ephemeral is affected by unrelated issues. This PR is safe enough to be merged without the PR check.

**Pull request merged**
