### PR TITLE
Notif 190 fix checkstyle location issue

### PR DESCRIPTION
**Pull request by bennetelli**

### CODE REVIEW

**Comment by theute** [comment]
Please always use the right JIRA ID format: ie `NOTIF-190` (not `Notif 190`) and don't re-include prior commits (and commit messages).

**Comment by theute** [comment]
And test locally as it still doesn't pass

**Comment by theute** [comment]
You could replace all the COPY commands to:
COPY . /home/jboss

**Comment by bennetelli** [comment]
tried it already. Still doesn't work. Will put checkstyle in every project again.

**Comment by theute** [comment]
Don't put the files in each project again, it builds without, just need to adapt the dockerfile

**Pull request merged**
