### PR TITLE
Override export service settings from env vars

### PR DESCRIPTION
**Pull request by gwenneg**

### CODE REVIEW

**Review by MikelAlejoBR — APPROVED** [review]
LGTM

**Comment by josejulio** [comment]
the ci build failed with the error:
```
16:46:22 ERROR: Step ?Publish JUnit test result report? failed: No test report files were found. Configuration error?
```

**Comment by josejulio** [comment]
it gets stuck on `12:07:36  #2 [internal] load build definition from Dockerfile.notifications-backend.jvm` I wonder if it's related to the changes :thinking:

**Comment by josejulio** [comment]
Tried on other PR and it's happening the same. Error seems unrelated to this PR but unsure if this is going to affect the deployment. Merging

**Pull request merged**
