### PR TITLE
NOTIF-190 fix checkstyle dockerfile issue

### PR DESCRIPTION
**Pull request by bennetelli**

### CODE REVIEW

**Comment by theute** [comment]
Please (again) use, the correct JIRA Id (Not `Notif 190` in Pull request name)
Then seems good to me

**Comment by bennetelli** [comment]
That's not me..

my commands in the console are:
git status
git add .
git commit -m "NOTIF-190 Fix checkstyle Dockerfile issue"
git push
git push --set-upstream origin NOTIF-190_Fix_Checkstyle_Dockerfile_issue

**Comment by bennetelli** [comment]
I don't know how to get rid of these commits. Without forking it I would just checkout the master again.
With the fork I tried to reset the latest commits, but as it looks like this didn't work. What can I do to get rid of it?

git reset --hard origin/master?

**Comment by theute** [comment]
It has to be you unless someone steals your keyboard :)

For this PR, just go ahead, but when you branch, you need to branch from master not from an older branch.

**Comment by bennetelli** [comment]
Regarding the Pull Request title.. I actually don't know what to do here.
I pasted everything from my console here and can't see what's wrong. In the commit as well as in the push of the branch.

**Comment by theute** [comment]
I fixed the title. The title of the PR is set by you when you open the PR, it defaults to the first commit text IIRC

**Comment by bennetelli** [comment]
Now I get it. Even if I do it like I did, when opening the PR, GitHub changes it and I need to check it before clicking on "create pull request".

**Pull request merged**
