### PR TITLE
Add PagerDuty to createEndpoint, fix severity enum

### PR DESCRIPTION
**Pull request by jessicarod7**
- Adds PagerDuty Endpoint to `EndpointRepository.createEndpoint` to be persisted
- Adds annotation `@Enumerated(EnumType.STRING)` to field `PagerDutyProperties#severity`
- Creates enum `PagerDutySeverityDTO` for properties DTO
- Fixes parsing of severity in `PagerDutyProcessor` (engine) and `PagerDutyTransformer` (connector) to ensure it remains in lowercase

### CODE REVIEW

**Review by MikelAlejoBR — APPROVED** [review]
LGTM!

**Comment by jessicarod7** [comment]
```java
2024-09-30 13:35:16,778 ERROR [com.red.clo.not.con.ExceptionProcessor] (Camel (camel-1) thread #26 - seda://engine-to-connector) Message sending failed on pagerduty: [orgId=null, historyId=7289ae8f-a457-462f-a75d-e45ccfaf5959, targetUrl=http://localhost:38881]: java.lang.IllegalArgumentException: No enum constant com.redhat.cloud.notifications.connector.pagerduty.PagerDutySeverity.warning
```

```java
[ERROR]   PagerDutyConnectorRoutesTest>ConnectorRoutesTest.testRedeliveredNotification:176->ConnectorRoutesTest.assertKafkaSinkIsSatisfied:360 Expected outcome starts: [unexpected end of stream, localhost:45379 failed to respond] - Actual outcome: No enum constant com.redhat.cloud.notifications.connector.pagerduty.PagerDutySeverity.warning
```

Lovely. It seems that `io.vertx.core.json.JsonObject` doesn't attempt to use the name set by ` com.fasterxml. jackson. annotation.JsonProperty`, so it doesn't try to serialize the enum. I'm just gonna override `toString` and leave a comment.

**Comment by jessicarod7** [comment]
```java
[ERROR]   PagerDutyConnectorRoutesTest>ConnectorRoutesTest.testRedeliveredNotification:176->ConnectorRoutesTest.assertKafkaSinkIsSatisfied:360 Expected outcome starts: [unexpected end of stream, localhost:45271 failed to respond] - Actual outcome: No enum constant com.redhat.cloud.notifications.connector.pagerduty.PagerDutySeverity.warning
```

I misinterpreted the error. It's reading the serialized "warning" from the JSON object, and trying to use that to match `PagerDutySeverity.WARNING`. The lowercase `PagerDutySeverity.warning` doesn't exist. Looking at a fix.

**Review by gwenneg — APPROVED** [review]
LGTM

**Pull request merged**
