### PR TITLE
NOTIF-270 Update template links

### PR DESCRIPTION
**Pull request by josejulio**

### CODE REVIEW

**Comment by theute** [comment]
@josejulio so I guess we can undraft and merge ?

**Comment by gwenneg** [comment]
Don't merge yet, I'm about to comment but I need to check something first :smiley:

**Comment by theute** [comment]
If the comment is that we should use a parameter for the hostname and use ci | qa | stage depending on the env, I agree :) I almost created a JIRA for it ;-)

**Review by gwenneg — COMMENTED** [review]
I don't know if that's out of the scope of this PR, but...
- `OApiService` contains a `https://cloud.redhat.com` url. Should it be updated?
- `RbacRestClientRequestFilter` also contains a (less important) check on `https://ci.cloud.redhat.com`. That same base path is present in `applications.properties` for the RBAC calls for CI.
- `clowdapp.yaml` contains a `cloud.redhat.com` API base path.

**Comment by gwenneg** [comment]
> If the comment is that we should use a parameter for the hostname and use ci | qa | stage depending on the env, I agree :) I almost created a JIRA for it ;-)

No but I completely agree with that! :smiley:

**Comment by josejulio** [comment]
> * `OApiService` contains a `https://cloud.redhat.com` url. Should it be updated?

IIUC, the API is still going to be on cloud.redhat.com - Only the UI is moving. console.redhat.com will be redirecting/proxying over to cloud.redhat.com.

Under that assumption it makes sense to leave it there.

> * `RbacRestClientRequestFilter` also contains a (less important) check on `https://ci.cloud.redhat.com`. That same base path is present in `applications.properties` for the RBAC calls for CI.

Same as above I think

> * `clowdapp.yaml` contains a `cloud.redhat.com` API base path.

I have no idea here :D

**Comment by theute** [comment]
For clowdapp, it's just a reversed DNS name but it won't change.
Yes API won't change now, only the UI

**Comment by josejulio** [comment]
> > If the comment is that we should use a parameter for the hostname and use ci | qa | stage depending on the env, I agree :) I almost created a JIRA for it ;-)
> 
> No but I completely agree with that!

https://issues.redhat.com/browse/POL-383

**Review by gwenneg — APPROVED** [review]

**Pull request merged**
