### PR TITLE
[ADR-46] Parametrize CPU and Memory resource usage in clowdapps

### PR DESCRIPTION
**Pull request by Fynardo**

### CODE REVIEW

**Comment by gwenneg** [comment]
Will other ClowdApp templates be updated in follow-up PRs?

**Comment by Fynardo** [comment]
> Will other ClowdApp templates be updated in follow-up PRs?

The idea was to create a commit per each clowdapp, but later I found that all of them were already properly parametrized

**Review by gwenneg — APPROVED** [review]
Sorry, I didn't notice this only changed the DB cleaner cronjob resources 😅

LGTM, thanks!

**Pull request merged**
