### PR TITLE
NOTIF-190 Temporarily remove Kafka topic interactions in backend and …

### PR DESCRIPTION
**Pull request by bennetelli**
…aggregator

### CODE REVIEW

**Review by gwenneg — COMMENTED** [review]
Why remove everything? The channel can simply be disabled like [this](https://github.com/RedHatInsights/notifications-backend/blob/master/backend/src/main/resources/application.properties#L37).

**Comment by bennetelli** [comment]
> Why remove everything? The channel can simply be disabled like [this](https://github.com/RedHatInsights/notifications-backend/blob/master/backend/src/main/resources/application.properties#L37).

Changed. Thanks for the hint :)

**Review by gwenneg — APPROVED** [review]
You may have a health check issue with `aggregator` because of the disabled channel. Reactive messaging may be reported as DOWN because all channels are disabled. But since that's only a temporary state, you can apply a temporary workaround: `quarkus.health.extensions.enabled=false`.

`backend` will be fine, we already have two disabled channels on prod.

**Review by gwenneg — APPROVED** [review]
LGTM

**Comment by bennetelli** [comment]
don't lgtm too early. The tests need to be green first ;)

**Comment by gwenneg** [comment]
I trusted the GH tests result :smile:

**Comment by gwenneg** [comment]
I shouldn't even LGTM a Draft :smiley:

**Comment by bennetelli** [comment]
haha :-D

**Pull request merged**
