### PR TITLE
Add pull request script file

### PR DESCRIPTION
**Pull request by bennetelli**

### CODE REVIEW

**Comment by bennetelli** [comment]
I am giving up... I don't get it. Whatever I do, I always have these other commits coming from somewhere.

**Comment by theute** [comment]
You can't give up or you'll never make a PR again ;-)
It's because you are not branching from RedHatInsights/notifications-backend/master

if `origin` is https://github.com/RedHatInsights/notifications-backend
and `bennetelli` is your fork then:

- make sure you are on master: git checkout master
- update master with any other changes from other developers: git pull origin master
- create a branch from master: git checkout -b "NOTIF-12345"
- make changes
- Git add your changes: git add . 
- Git commit your changes: git commit -m "NOTIF-12345 my changes"
- Push your changes: git push bennetelli
- Open the PR as proposed in GitHub

But looking at your master it is not in sync with origin/master so you may need a `git reset --hard origin/master` to start with.

**Comment by bennetelli** [comment]
I was giving up for yesterday. Generally giving up is not an option ;-)

Thanks for your explanation

**Comment by bennetelli** [comment]
Even with your descirption there, it doesn't work.

**Pull request closed without merging**
