### PR TITLE
Repair Flyway migration

### PR DESCRIPTION
**Pull request by gwenneg**
https://flywaydb.org/documentation/command/repair

### CODE REVIEW

**Comment by gwenneg** [comment]
@theute This will repair the Flyway repair the schema history table. We should deploy it once, then redeploy without the repair feature.

**Comment by josejulio** [comment]
> @theute This will repair the Flyway schema history table. We should deploy it once, then redeploy without the repair feature.

We might need this for prod too

**Review by josejulio — APPROVED** [review]
lgtm

**Comment by gwenneg** [comment]
We can revert this change after the V1.6.0 is done in prod.

**Pull request merged**
