### PR TITLE
Downgrade base images to ubi8

### PR DESCRIPTION
**Pull request by g-duval**

### CODE REVIEW

**Comment by gwenneg** [comment]
`Dockerfile.notifications-connector-pagerduty` will need to be downgraded too.

**Comment by gwenneg** [comment]
What about the instructions such as
```
RUN rpm -e --nodeps platform-python-setuptools
```
which were removed in 2906. Do we need them back?

**Comment by g-duval** [comment]
> What about the instructions such as
> 
> ```
> RUN rpm -e --nodeps platform-python-setuptools
> ```
> 
> which were removed in #2906. Do we need them back?

No it seems has been fixed on recent ubi8 images

**Review by gwenneg — APPROVED** [review]
LGTM

**Comment by gwenneg** [comment]
Failures in Konflux are unrelated.

**Pull request merged**
