### PR TITLE
fix(rhosak): change Kafka by Openhift Streams in action required email Subject

### PR DESCRIPTION
**Pull request by machi1990**

### CODE REVIEW

**Review by gwenneg — APPROVED** [review]
LGTM

**Comment by gwenneg** [comment]
@machi1990 Feel free to merge when all checks are successful.

**Comment by gwenneg** [comment]
Actually, I'm not sure if you have the permission to merge in this repo. Do you ?

**Comment by machi1990** [comment]
> Actually, I'm not sure if you have the permission to merge in this repo. Do you ?

No, I do not have permissions.

**Pull request merged**
