### PR TITLE
Allow HTTP endpoint to talk to HTTPS sites

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Comment by ShimShtein** [comment]
Why not using [https_endpoint](https://github.com/RedHatInsights/notifications-backend/blob/master/app/models/endpoints/https_endpoint.rb)?

**Comment by ShimShtein** [comment]
Adding @bastilian, since it can be implemented on client side.

**Comment by ShimShtein** [comment]
If we want an automatic selection between http and https, we can do it in the [controller](https://github.com/RedHatInsights/notifications-backend/blob/master/app/controllers/endpoints_controller.rb#L67).

One thing that we need to change is the default behaviour for [`certificate_chain`](https://github.com/RedHatInsights/notifications-backend/blob/master/app/models/endpoints/https_endpoint.rb#L39). Right now we require explicit certificate chain, but if this is not desired, and for default case we want to use system's default CA's, we can use [`set_default_paths`](https://docs.ruby-lang.org/en/2.4.0/OpenSSL/X509/Store.html) if no certificate was given (as you try in this PR).

**Comment by adamruzicka** [comment]
> Why not using https_endpoint?

It was bigger change than just letting the HTTP endpoint talk to HTTPS sites without checking their certs

**Comment by ShimShtein** [comment]
Merged, thanks @adamruzicka!

**Pull request merged**
