### PR TITLE
Add platsec workflow

### PR DESCRIPTION
**Pull request by gburges**

### CODE REVIEW

**Comment by josejulio** [comment]
Some of the vulnerabilities mention pip/python.
I checked it offline and `java-17-openjdk-headless` installs some python libs:

```
# microdnf install java-17-openjdk-headless

(microdnf:73): librhsm-WARNING **: 17:09:03.510: Found 0 entitlement certificates

(microdnf:73): librhsm-WARNING **: 17:09:03.510: Found 0 entitlement certificates
Package                                                                                                                                                            Repository                                                       Size
Installing:                                                                                                                                                                                                                             
 alsa-lib-1.2.8-2.el8.x86_64                                                                                                                                       ubi-8-appstream-rpms                                         508.5 kB
 avahi-libs-0.7-20.el8.x86_64                                                                                                                                      ubi-8-baseos-rpms                                             63.1 kB
 copy-jdk-configs-4.0-2.el8.noarch                                                                                                                                 ubi-8-appstream-rpms                                          31.3 kB
 crypto-policies-scripts-20221215-1.gitece0092.el8.noarch                                                                                                          ubi-8-baseos-rpms                                             85.9 kB
 cups-libs-1:2.2.6-51.el8_8.1.x86_64                                                                                                                               ubi-8-baseos-rpms                                            445.4 kB
 dbus-libs-1:1.12.8-24.el8_8.1.x86_64                                                                                                                              ubi-8-baseos-rpms                                            189.4 kB
 expat-2.2.5-11.el8.x86_64                                                                                                                                         ubi-8-baseos-rpms                                            116.1 kB
 findutils-1:4.6.0-20.el8.x86_64                                                                                                                                   ubi-8-baseos-rpms                                            540.8 kB
 gdbm-1:1.18-2.el8.x86_64                                                                                                                                          ubi-8-baseos-rpms                                            132.8 kB
 gdbm-libs-1:1.18-2.el8.x86_64                                                                                                                                     ubi-8-baseos-rpms                                             61.8 kB
 java-17-openjdk-headless-1:17.0.8.0.7-2.el8.x86_64                                                                                                                ubi-8-appstream-rpms                                          48.8 MB
 javapackages-filesystem-5.3.0-1.module+el8+2447+6f56d9a6.noarch                                                                                                   ubi-8-appstream-rpms                                          31.1 kB
 libnsl2-1.2.0-2.20180605git4a062cf.el8.x86_64                                                                                                                     ubi-8-baseos-rpms                                             59.1 kB
 libtirpc-1.1.4-8.el8.x86_64                                                                                                                                       ubi-8-baseos-rpms                                            115.8 kB
 lksctp-tools-1.0.18-3.el8.x86_64                                                                                                                                  ubi-8-baseos-rpms                                            101.9 kB
 lua-5.3.4-12.el8.x86_64                                                                                                                                           ubi-8-appstream-rpms                                         197.0 kB
 nspr-4.34.0-3.el8_6.x86_64                                                                                                                                        ubi-8-appstream-rpms                                         146.5 kB
 nss-3.79.0-11.el8_7.x86_64                                                                                                                                        ubi-8-appstream-rpms                                         765.2 kB
 nss-softokn-3.79.0-11.el8_7.x86_64                                                                                                                                ubi-8-appstream-rpms                                           1.3 MB
 nss-softokn-freebl-3.79.0-11.el8_7.x86_64                                                                                                                         ubi-8-appstream-rpms                                         407.8 kB
 nss-sysinit-3.79.0-11.el8_7.x86_64                                                                                                                                ubi-8-appstream-rpms                                          76.4 kB
 nss-util-3.79.0-11.el8_7.x86_64                                                                                                                                   ubi-8-appstream-rpms                                         142.0 kB
 platform-python-3.6.8-51.el8_8.1.x86_64                                                                                                                           ubi-8-baseos-rpms                                             88.6 kB
 platform-python-pip-9.0.3-22.el8.noarch                                                                                                                           ubi-8-baseos-rpms                                              1.7 MB
 platform-python-setuptools-39.2.0-7.el8.noarch                                                                                                                    ubi-8-baseos-rpms                                            647.4 kB
 python3-libs-3.6.8-51.el8_8.1.x86_64                                                                                                                              ubi-8-baseos-rpms                                              8.2 MB
 python3-pip-wheel-9.0.3-22.el8.noarch                                                                                                                             ubi-8-baseos-rpms                                            916.3 kB
 python3-setuptools-wheel-39.2.0-7.el8.noarch                                                                                                                      ubi-8-baseos-rpms                                            296.0 kB
 tzdata-java-2023c-1.el8.noarch                                                                                                                                    ubi-8-appstream-rpms                                         191.1 kB
Transaction Summary:
 Installing:       29 packages
 Reinstalling:      0 packages
 Upgrading:         0 packages
 Obsoleting:        0 packages
 Removing:          0 packages
 Downgrading:       0 packages
Enabling module streams:
    javapackages-runtime:201801

```

Also found [this](https://www.reddit.com/r/redhat/comments/x81ep6/comment/inglcvo/?utm_source=reddit&utm_medium=web2x&context=3).

**Review by gwenneg — APPROVED** [review]
LGTM

**Comment by gwenneg** [comment]
I'm testing the scans in https://github.com/RedHatInsights/notifications-backend/pull/2082

**Comment by gwenneg** [comment]
Python is gone with the new base image from https://github.com/RedHatInsights/notifications-backend/pull/2082, which has yet to be tested in stage.

I'll merge this PR as it seems ready.

**Pull request merged**
