### PR TITLE
[RHCLOUD-25512] Fix emails rendering with MS Outlook client

### PR DESCRIPTION
**Pull request by g-duval**

### CODE REVIEW

**Comment by gwenneg** [comment]
@g-duval This PR needs a rebase because of the recent Patch template update.

**Comment by gwenneg** [comment]
Will the changes here need to be validated by someone outside of our dev team?

**Comment by g-duval** [comment]
@gwenneg Sure, I rebased it. Those change are only about CSS to be rendered properly on Outlook.
I validated changes using Email On Acid.

**Review by gwenneg — APPROVED** [review]
I haven't seen the rendered HTML but from a code/CSS perspective, LGTM!

**Pull request merged**
