### PR TITLE
Add search by url and name to endpoints

### PR DESCRIPTION
**Pull request by ShimShtein**

### CODE REVIEW

**Comment by ShimShtein** [comment]
@bastilian, can you try to work with this search convention: `endpoints?q=url~bleh`?

**Comment by bastilian** [comment]
@ShimShtein It would be great if `?q=TERM` would search in both, `name` and `url`.

**Comment by ShimShtein** [comment]
@bastilian, Done.

**Comment by bastilian** [comment]
Thanks @ShimShtein! Works great!

**Pull request merged**
